### PR TITLE
Add a noteboook for enhanced sampling tutorials 

### PR DESCRIPTION
**Pull request by sukritsingh**
Here's an initial (rough) draft of a cookbook for running enhanced sampling methods (AMD, GAMD, MetaD, and Umbrella Sampling) using OpenMM. I was thinking about adding a set of code for running SAMS from OpenMMTools but I wasn't sure if that would be a good fit here because it uses OpenMMTools? Are there thoughts here? 

This submission is response to a larger effort to add more tutorials to the OpenMM-cookbook #12 

Any and all feedback welcome! Thanks so much!

### CODE REVIEW

**Comment by sef43** [comment]
Hi @sukritsingh, thanks for these!

I think we could add a section to the cookbook called "Enhanced sampling methods" we can then have multiple separate short note books for "Setting up a CV", "AMD", "Metadynamics", "Umbrella sampling" where they show the setup phase but only run for a few steps. We can then add some tutorials which have longer runtime and show some example analysis of these types of simulations

**Comment by sef43** [comment]
also my opinion is that use of openmm-tools (and other python packages) is fine for tutorials but should be avoided for cookbook recipes

**Comment by sukritsingh** [comment]
Sure! I'm guessing this is all based on the merging of PR #16 ? My plan would then be to then create a subdirectory in `cookbook` called "Enhanced sampling methods" and then make these small notebooks that you mentioned? From there I can craft some tutorials for longer simulations + analysis in a separate PR? 

>also my opinion is that use of openmm-tools (and other python packages) is fine for tutorials but should be avoided for cookbook recipes

Sounds good. This would mainly be for either SAMS or Adaptive Sampling approaches, which use OpenMMTools or PyEmma...these would be for a further PR down the road anyways. 

Anyways if there are no objections I'll get started on this!

**Comment by sef43** [comment]
> Sure! I'm guessing this is all based on the merging of PR #16 ? My plan would then be to then create a subdirectory in `cookbook` called "Enhanced sampling methods" and then make these small notebooks that you mentioned? From there I can craft some tutorials for longer simulations + analysis in a separate PR?
> 
> > also my opinion is that use of openmm-tools (and other python packages) is fine for tutorials but should be avoided for cookbook recipes
> 
> Sounds good. This would mainly be for either SAMS or Adaptive Sampling approaches, which use OpenMMTools or PyEmma...these would be for a further PR down the road anyways.
> 
> Anyways if there are no objections I'll get started on this!

Yes that all sounds great!

**Comment by sukritsingh** [comment]
Due to the merge conflicts github seemed to want me to close this PR and open a fresh one (#21 ) - so I've done that for review!

**Pull request closed without merging**
