### PR TITLE
Add tutorials

### PR DESCRIPTION
**Pull request by sef43**
* split cookbook and tutorials into two different pages
 * add new basic introductionary tutorial
 * add the old OpenMM 7 tutorials as is from existing docs

### CODE REVIEW

**Comment by peastman** [comment]
Is the above link supposed to work?  It produces a 404.

**Comment by sef43** [comment]
> Is the above link supposed to work? It produces a 404.

It is supposed to, but it doesn't work, also gives me 404

**Comment by sef43** [comment]
@peastman the link for the rendered PR now works: https://openmm.github.io/openmm-cookbook/PR16/index.html

**Comment by peastman** [comment]
It still presents them on a single page titled "The OpenMM Cookbook and Tutorials".

**Comment by sef43** [comment]
@peastman @jchodera Are you happy with the setup?, the [index page](https://openmm.github.io/openmm-cookbook/PR16/index.html) has separate links to the cookbook and tutorials pages. These separate pages can be directly linked to: [cookbook](https://openmm.github.io/openmm-cookbook/PR16/cookbook.html), [tutorials](https://openmm.github.io/openmm-cookbook/PR16/tutorials.html)

**Comment by peastman** [comment]
Sorry for not getting to this sooner!  It's looking good.  How do you envision integrating this with the rest of the website?  Currently the tutorials are [their own tab](https://openmm.org/tutorials), while the cookbook is linked from [the documentation tab](https://openmm.org/documentation).  Do we want to keep that organization?  Should the tutorials become another link from the documentation tab?  Should the cookbook and/or tutorials be added to the sidebar in the other documentation (see for example http://docs.openmm.org/latest/userguide/)?

**Comment by peastman** [comment]
That sounds reasonable.

A very minor bug: on the tutorials page, the label at the top left says "OpenMM Cookbook" instead of "OpenMM Tutorials".

**Comment by sef43** [comment]
> A very minor bug: on the tutorials page, the label at the top left says "OpenMM Cookbook" instead of "OpenMM Tutorials".

I've changed the top left label by the OpenMM logo to read "OpenMM Cookbook and Tutorials", The sidebar navigation and main page title makes it clear if you are in the cookbook or the tutorials, I don't think its possible so set it differently for each page given they are being built in the same sphinx document.

**Pull request merged**
