### PR TITLE
Adding tutorials to cookbook

### PR DESCRIPTION
**Pull request by sef43**
I have added the tutorials from https://openmm.org/tutorials to the cookbook. 

As they require some proper compute time I have set them to not be run through the CI when building. This is done with the metadata tag   
```
"nbsphinx": {
   "execute": "never"
  },
```
Also I have changed the CI yaml files to just run pytest on the notebooks/cookbooks and not notebooks/tutorials which contain the tutorials.

Also added the first example from the user guide to the cookbook.

You can see this fork version at 
https://sef43.github.io/openmm-cookbook/dev/index.html

### CODE REVIEW

**Comment by sef43** [comment]
Tagging @jchodera for coordinating

**Comment by jchodera** [comment]
@sef43 : Apologies for taking so long to get back to you about this.

Thanks so much for this! I think this is a great improvement, and I like the way you've structured everything, with first steps at the top and more detailed tutorials at the end. I suggest we try to get this merged and then we can refine the categories/structure later.

The tutorials will need some more cleanup before they are ready, but I'm happy to take a stab at that. Is it possible to split the PR into just the structural changes, and then add the tutorials in a separate PR via a branch from this repo? In principle, [the deployment scripts](https://github.com/openmm/openmm-cookbook/blob/f955870c0908973ecde27fe09cd81efc927664d1/.github/workflows/gh-pages.yml#L57-L90) should create a [`PR#/`](https://github.com/openmm/openmm-cookbook/blob/f955870c0908973ecde27fe09cd81efc927664d1/.github/workflows/gh-pages.yml#L64-L70) path for the PR, but something seems to be broken and only the [`dev/`](https://github.com/openmm/openmm-cookbook/blob/f955870c0908973ecde27fe09cd81efc927664d1/.github/workflows/gh-pages.yml#L57-L63) deployment is working right now. If you could manage to get this working, it will be much easier to get these sorted.

**Comment by sef43** [comment]
@jchodera I have split this PR into just the structural changes. The PR13/ pages deployment is failing from a permission denied error: 
```
  remote: Permission to openmm/openmm-cookbook.git denied to github-actions[bot].
```
I think this is because this is a PR from my personal fork. The PR deployment will only work from a branch of openmm/openmm-cookbook. I suggest either we merge this, or I can create the same pull request from a new branch of the main repo instead.

**Comment by jchodera** [comment]
This looks great! I'll merge it now. 

How about we make future PRs from branches of this repo to make it easier to test?

**Review by jchodera — APPROVED** [review]
This is a huge improvement! Thanks so much!

**Comment by peastman** [comment]
I somehow missed this when it was posted.  I'm not sure what happened.  Sorry about that, whatever it was.

Anyway, the tutorials and the cookbook should be kept separate from each other and go on different pages.  They use the same technology and can be built at the same time, but they're different things that serve different purposes.  Mixing them together on a single page would make both of them less useful.

**Comment by sef43** [comment]
> I somehow missed this when it was posted. I'm not sure what happened. Sorry about that, whatever it was.
> 
> Anyway, the tutorials and the cookbook should be kept separate from each other and go on different pages. They use the same technology and can be built at the same time, but they're different things that serve different purposes. Mixing them together on a single page would make both of them less useful.

@peastman are you proposing we make a new repo and webpage that is https://openmm.github.io/openmm-tutorials, and we use the same template as the cookbook uses?

**Comment by peastman** [comment]
No need for a new repo or anything like that.  I just mean that on the website there should be one page for tutorials and a different page for cookbook recipes (the same as there is now).  They can both get built at the same time, just from different folders in the same repo.

**Pull request merged**
